### ISSUE TITLE
Game over for no apparent reason

### ISSUE THREAD

**Issue by janprzy** [vicgeralds/vitetris#10]
I was just playing vitetris on Linux, when the game suddenly stopped and a "GAME OVER" message appeared, although I hadn't reached the top. This has, so far, happened twice in a row.
I have also played it on a Mac, where this issue was not present.

For debugging purposes, are there any logs I could post?

![Screenshot_2019-09-29 _22:17:50](https://user-images.githubusercontent.com/41625296/65838790-1a7a2700-e307-11e9-9920-7e8cda4f1518.png)

**Comment by vicgeralds** [comment]
That's annoying. I've tried read the code to understand what could cause this, but couldn't find any clues really.

If you can still reproduce this bug or have some other information that you think could help, there might be a chance to fix it. There's no debugging logs, I would just try to reproduce the error using a debugger.

Otherwise, I'm afraid this is a rare bug that's not worth fixing.

**Comment by vicgeralds** [comment]
I finally noted something strange in the screenshot. Lines is showing "000". If you are playing B-type and just completed 25 lines, then game over is actually normal.

I know this is confusing. The message should probably say, "CONGRATS! You successfully cleared 25 lines!" or something. Also, while playing it's not obvious which game mode you selected.

**Comment by janprzy** [comment]
Wow, you're right, I had accidentally switched to B-type! After switching back to A-type everything works as expected.
